{% set name = "backports.strenum" %}
{% set version = "1.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backports_strenum-{{ version }}.tar.gz
  sha256: 4dd47365fd427ac8028aeb1ad3628ea38e67c4d0336ceebd5c0f113e0c487ce9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.6,<4.0.0

test:
  imports:
    - backports.strenum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/clbarnes/backports.strenum
  summary: Base class for creating enumerated constants that are also subclasses of str
  license: EPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tadeu
